//! Pokémon **Yellow Legacy** overlay — the concrete filling of the core↔overlay
//! seam ([`crate::core::data`]).
//!
//! This module is the **sole owner** of Yellow-Legacy-specific data. It turns the
//! generated id→name tables (in the `generated/` subdir) into implementations of
//! [`SpeciesTable`], [`MoveTable`], and [`ItemTable`], and encodes the
//! Legacy-specific constants (bag capacity, badge stat-boost multipliers,
//! difficulty mode) that the core deliberately does not carry.
//!
//! # Data provenance
//! The name tables come from the pinned Pokémon Yellow Legacy disassembly
//! (`vendor/pokemon-yellow-legacy`), emitted as JSON by the `xtask` dev tool.
//! **Regenerate on a ROM-version bump** with `cargo run -p xtask`. See
//! `generated/README.md` for details.
//!
//! # Scope
//! Only name resolution and a handful of encoded constants live here.
//! A `TypeChart` / type-coverage feature is deferred (out of Milestone-1 scope).

use std::collections::HashMap;

use crate::core::data::{ItemTable, MoveTable, SpeciesTable};

/// The Yellow Legacy game-data overlay: owned id→name tables plus this
/// module's Legacy constants, satisfying [`GameData`](crate::core::data::GameData)
/// via the blanket impl.
pub struct YellowLegacy {
    species: HashMap<u8, String>,
    moves: HashMap<u8, String>,
    items: HashMap<u8, String>,
}

impl YellowLegacy {
    /// Bag capacity in Yellow Legacy.
    ///
    /// Legacy raises the bag from vanilla's 20 to **41** items — see
    /// `reference/YELLOW_LEGACY_PORTABLE_NOTES.md` §"Bag capacity is 41 items in
    /// Legacy (vs vanilla 20)".
    pub const BAG_CAPACITY: usize = 41;

    /// Per-badge in-battle stat-boost multiplier (×1.125 per applicable badge).
    ///
    /// From `reference/YELLOW_LEGACY_PORTABLE_NOTES.md` §2: four gym badges each
    /// passively boost one stat of the active mon in battle by ×1.125 (confirmed
    /// in `ApplyBadgeStatBoosts`).
    pub const BADGE_BOOST: f32 = 1.125;

    /// Legacy's Pikachu-specific badge stat-boost multiplier (×1.25).
    ///
    /// From `reference/YELLOW_LEGACY_PORTABLE_NOTES.md` §2: a LEGACY tweak — for
    /// **Pikachu specifically** the per-badge boost is ×1.25 instead of ×1.125
    /// (a nod to Yellow's mascot; `cp PIKACHU → extra shift` in
    /// `ApplyBadgeStatBoosts`).
    pub const PIKACHU_BADGE_BOOST: f32 = 1.25;

    /// Load the overlay from the compile-time-embedded generated JSON tables.
    ///
    /// # Panics
    /// Panics if any embedded table fails to parse. The JSON is generated by
    /// `xtask` and embedded at build time, so a parse failure is a build-time
    /// *data* bug (a bad regeneration), not a runtime input error — a panic here
    /// is clearer than threading a `Result` through every caller of an
    /// infallible-in-practice constructor. All ids fit in `u8` (max item id 250
    /// < 256, verified in Task 12), so the `HashMap<u8, String>` key parse cannot
    /// legitimately overflow; if it ever did, that too is a data bug worth
    /// panicking on.
    pub fn new() -> Self {
        Self {
            species: parse_table(include_str!("generated/species.json"), "species"),
            moves: parse_table(include_str!("generated/moves.json"), "moves"),
            items: parse_table(include_str!("generated/items.json"), "items"),
        }
    }
}

/// Parse one embedded JSON id→name table, panicking (with a table label) on
/// failure — see [`YellowLegacy::new`] for why a panic is the right call.
fn parse_table(json: &str, label: &str) -> HashMap<u8, String> {
    serde_json::from_str(json)
        .unwrap_or_else(|e| panic!("generated {label} table failed to parse: {e}"))
}

impl Default for YellowLegacy {
    fn default() -> Self {
        Self::new()
    }
}

impl SpeciesTable for YellowLegacy {
    fn species_name(&self, id: u8) -> Option<&str> {
        self.species.get(&id).map(String::as_str)
    }
}

impl MoveTable for YellowLegacy {
    fn move_name(&self, id: u8) -> Option<&str> {
        self.moves.get(&id).map(String::as_str)
    }
}

impl ItemTable for YellowLegacy {
    fn item_name(&self, id: u8) -> Option<&str> {
        self.items.get(&id).map(String::as_str)
    }
}

/// Yellow Legacy's difficulty mode (`wDifficulty`).
///
/// Legacy adds a hard mode that branches real mechanics (e.g. the level cap;
/// see `reference/YELLOW_LEGACY_PORTABLE_NOTES.md` §1).
///
/// # Deferred
/// Reading the active difficulty from a save is **not yet implemented** — it
/// requires locating `wDifficulty`'s saved offset in the disassembly. This enum
/// only *defines* the modes; no offset is invented here.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Difficulty {
    /// Normal mode (no level cap; standard mechanics).
    Normal,
    /// Hard mode (level-capped and other branched mechanics).
    Hard,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::data::GameData;

    #[test]
    fn species_name_resolves_known_id() {
        assert_eq!(YellowLegacy::new().species_name(131), Some("MEWTWO"));
    }

    #[test]
    fn move_name_resolves_known_id() {
        assert_eq!(YellowLegacy::new().move_name(85), Some("THUNDERBOLT"));
    }

    #[test]
    fn item_name_resolves_known_id() {
        assert_eq!(YellowLegacy::new().item_name(1), Some("MASTER BALL"));
    }

    #[test]
    fn unknown_ids_resolve_to_none() {
        let g = YellowLegacy::new();
        // species 0 is the null id (no internal species there).
        assert_eq!(g.species_name(0), None);
        // item 99 falls in a floor-gap between regular items (≤83) and HMs (196+).
        assert_eq!(g.item_name(99), None);
    }

    /// Prove the overlay composes as the aggregate: a fn bound only on
    /// `GameData` accepts `&YellowLegacy` (which never impls `GameData`
    /// explicitly — the blanket impl supplies it).
    fn uses_game_data(g: &dyn GameData) -> (Option<&str>, Option<&str>, Option<&str>) {
        (g.species_name(131), g.move_name(85), g.item_name(1))
    }

    #[test]
    fn composes_as_game_data() {
        assert_eq!(
            uses_game_data(&YellowLegacy::new()),
            (Some("MEWTWO"), Some("THUNDERBOLT"), Some("MASTER BALL"))
        );
    }

    #[test]
    fn legacy_constants() {
        assert_eq!(YellowLegacy::BAG_CAPACITY, 41);
        assert_eq!(YellowLegacy::BADGE_BOOST, 1.125);
        assert_eq!(YellowLegacy::PIKACHU_BADGE_BOOST, 1.25);
    }

    #[test]
    fn difficulty_has_normal_and_hard_variants() {
        let normal = Difficulty::Normal;
        let hard = Difficulty::Hard;
        assert_ne!(normal, hard);
        // round-trip through serde to prove the derive is wired up.
        assert_eq!(serde_json::to_string(&normal).unwrap(), "\"Normal\"");
        assert_eq!(
            serde_json::from_str::<Difficulty>("\"Hard\"").unwrap(),
            Difficulty::Hard
        );
    }

    #[test]
    fn tables_load_expected_counts() {
        let g = YellowLegacy::new();
        assert_eq!(g.species.len(), 190);
        assert_eq!(g.moves.len(), 165);
        assert_eq!(g.items.len(), 138);
    }
}
